### ISSUE TITLE
hide "get new" link

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tom-james-watson/old-reddit-redirect#50]
This
![get-new](https://user-images.githubusercontent.com/4629794/121740889-be9c0580-cacb-11eb-8c91-d2a2d698c0b0.png)

can be removed with this
```css
#redesign-beta-optin-btn { display: none; }
```
